Restore menu planner.

diff --git a/.github/workflows/chef.yml b/.github/workflows/chef.yml
--- a/.github/workflows/chef.yml
+++ b/.github/workflows/chef.yml
@@ -81,25 +81,19 @@ jobs:
         
         # Tell Copilot to generate the weekly menu plan
         echo "Getting weekly menu plan"
-        copilot --model=${{ env.COPILOT_MODEL }} --agent=chef --allow-all-tools --prompt "Create a file named 'bar.txt'. Then create a directory named 'foo' and move 'bar.txt' into it."
-        ls -l
-        
-        cat session.log
-        cat tool-usage.log
+        copilot --model=${{ env.COPILOT_MODEL }} --agent=chef --allow-tool 'write' --prompt "Provide a new menu plan, please"
+        GENERATED_PLAN=$(cat menu_plans/MENU_PLAN_$DATE.md)
 
-        # copilot --model=${{ env.COPILOT_MODEL }} --agent=chef --allow-tool 'write' --prompt "Provide a new menu plan, please"
-        # GENERATED_PLAN=$(cat menu_plans/MENU_PLAN_$DATE.md)
+        # Save plan or exit if failed
+        if [[ "$GENERATED_PLAN" =~ "Weekly Menu Plan" ]]; then
+          echo "Menu plan generated successfully. Pushing changes."
 
-        # # Save plan or exit if failed
-        # if [[ "$GENERATED_PLAN" =~ "Weekly Menu Plan" ]]; then
-        #   echo "Menu plan generated successfully. Pushing changes."
-
-        #   # Save plan for further outputs
-        #   echo "$GENERATED_PLAN" >> $GITHUB_STEP_SUMMARY
-        # else
-        #   echo "Failed to generate menu plan. Exiting."
-        #   exit 1
-        # fi
+          # Save plan for further outputs
+          echo "$GENERATED_PLAN" >> $GITHUB_STEP_SUMMARY
+        else
+          echo "Failed to generate menu plan. Exiting."
+          exit 1
+        fi
         
     # # Push changes to remote repository
     # - name: Push changes
