Enhance menu plan generation: improve output handling and add success message

diff --git a/.github/workflows/chef.yml b/.github/workflows/chef.yml
--- a/.github/workflows/chef.yml
+++ b/.github/workflows/chef.yml
@@ -75,26 +75,28 @@ jobs:
         echo "Getting weekly menu plan"
         git status  # View the current branch
         GENERATED_PLAN=$(copilot --model=${{ env.COPILOT_MODEL }} --agent=chef --allow-all-tools --prompt "Provide a new menu plan, please")
-        
+        echo "Menu plan generated successfully. Pushing changes."
+
         # Save plan for further outputs
-        echo $GENERATED_PLAN >> $GITHUB_STEP_SUMMARY
+        echo "$GENERATED_PLAN" >> $GITHUB_STEP_SUMMARY
+        
+        # This to avoid issues with multiline outputs
         echo "GENERATED_PLAN<<EOF" >> $GITHUB_OUTPUT
         echo "$GENERATED_PLAN" >> $GITHUB_OUTPUT
         echo "EOF" >> $GITHUB_OUTPUT
-        echo "Menu plan generated successfully. Pushing changes."
         
-        # Commit and push changes
-        git add MENU_PLAN_*.md
-        git commit -m "Add weekly menu plan"
-        git push origin HEAD
+        # # Commit and push changes
+        # git add MENU_PLAN_*.md
+        # git commit -m "Add weekly menu plan"
+        # git push origin HEAD
 
     # Create Pull Request
-    - name: Create Pull Request
-      shell: bash
-      run: |
-        # Propagate errors and exit in case of failure
-        set -euo pipefail
+    # - name: Create Pull Request
+    #   shell: bash
+    #   run: |
+    #     # Propagate errors and exit in case of failure
+    #     set -euo pipefail
 
-        # Create a Pull Request using GH CLI
-        echo "Creating Pull Request"
-        gh pr create --base main --title "Weekly Menu Plan" --body $'This PR contains the proposed menu plan for the week generated by the Chef agent:\n\n${{ steps.get_menu_plan.outputs.GENERATED_PLAN }}'
+    #     # Create a Pull Request using GH CLI
+    #     echo "Creating Pull Request"
+    #     gh pr create --base main --title "Weekly Menu Plan" --body $'This PR contains the proposed menu plan for the week generated by the Chef agent:\n\n${{ steps.get_menu_plan.outputs.GENERATED_PLAN }}'
